name: check
on:
  pull_request:
    paths:
      - '**.md'

jobs:
    alex:
      runs-on: ubuntu-latest
      steps:
        # Checkout codebase
        - uses: actions/checkout@v1

        - name: Install alex
          run: yarn install alex

        - name: alex
          run: |
            echo "::add-matcher::.github/alex.json"
            yarn alex
